from class_try_exception_ import error_site

import requests
from bs4 import BeautifulSoup

def main():
   
    error_site.site()

if __name__ == '__main__':
    main()
